### ISSUE TITLE
Allow for task coalescing

### ISSUE THREAD

**Issue by sdgandhi** [THREDOpenSource/SYNQueue#5]
Task coalescing per task type. I have a few implementation methods in mind. But need to think on it a bit more.

**Comment by jhurliman** [comment]
What about a user defined callback that takes two tasks and returns one (merge operator)?

**Comment by sdgandhi** [comment]
After further analysis, I don't think it makes sense to support this. It's a minor use case in most applications and complicating the queue logic for it doesn't make sense. We can open this again if we have more interest in the future.
